### ISSUE TITLE
No normalize css

### ISSUE THREAD

**Issue by Sambillingham** [steersystems/beyond#111]
For some reason my local development is looking for a standalone normalize.css when it should be bundled in with the sass compilation. I can't seem to figure out what is going on, production is unaffected is it just me?

![screen shot 2015-10-28 at 14 26 22](https://cloud.githubusercontent.com/assets/2798285/10791369/0a9562aa-7d80-11e5-91a1-ef6637ba517f.png)

**Comment by samjbmason** [comment]
So we figured this is because of the difference betweent he two gulp tasks. I looked it up and can see this is widely reported issue (http://stackoverflow.com/questions/27727803/gulp-sass-import-css-file).

Proposed solution: We use minifyCSS gulp in the build task for dev but use source maps so we can still debug successfully

**Comment by Sambillingham** [comment]
Sounds like a good plan
