### ISSUE TITLE
Open Graph data not being scrapped 

### ISSUE THREAD

**Issue by Sambillingham** [steersystems/beyond#37]
What I see: When sharing via Facebook or using the debugger tool at (https://developers.facebook.com/tools/debug/og/object/)  no information can be picked up
What I expect: data from og:title, og:description, og:image to be used.

Fix: Facebook debugger is complaining about the og:title tag not being present but it clearly is in the source. We are missing an og:url tag, wonder if that might be want is causing the issue. 

<img width="727" alt="screen shot 2015-09-26 at 09 00 37" src="https://cloud.githubusercontent.com/assets/2798285/10116430/1cce0fd8-642d-11e5-9615-a524b277be96.png">

**Comment by Sambillingham** [comment]
added the type:url - loses the og:type error but still no luck on getting a scrape

**Comment by Sambillingham** [comment]
Some suggest the issue might be with DNS :confused: 
<img width="870" alt="screen shot 2015-09-26 at 11 50 50" src="https://cloud.githubusercontent.com/assets/2798285/10117224/0f284212-6447-11e5-98d2-465b1b231958.png">
<img width="735" alt="screen shot 2015-09-26 at 12 06 00" src="https://cloud.githubusercontent.com/assets/2798285/10117225/0f286634-6447-11e5-924a-b058e4f7e2d8.png">

Any chance you can have a look @samjbmason

**Comment by samjbmason** [comment]
So looking into this, we are getting 302 redirects which FB hates and doesn't follow. These 302's are coming from our records being pointed at Github's Servers ip addresses. They have implemented Denial of Service protection which creates this redirect. 

Unfortunately the only way around it seems to be find a DNS provider which supports ALIAS records. Gandi does not nor does Cloudflare. http://subosito.com/github-hosted-redirect/

However, all the examples I have seen are using it with a top level Github Pages sites e.g `steersystems.github.io` I'm unsure whether this solution will work with `steersystems.github.io/beyond`

**Comment by samjbmason** [comment]
Okey dokey, this is all solved now. The problem was indeed due to Github Pages implementing a 302 redirect to help with their DDOS attack mitigation system that they implemented, while it helps to ensure Github doesn't get taken down nor sites hosted on their servers it does cause services like facebook and twitter's open graphs to fall over as they don't like going past the 302 redirect.

The solution to this would be to use a ALIAS record in our DNS to point to `steersystems.github.io` rather than the ip addresses of Githubs servers. However, ALIAS records arent available on Gandi who host our DNS. So instead I have changed our DNS to Cloudlfare and have signed us up to a free plan there which implements a similar thing to ALIAS records.

I have configured it and can confirm it's working and that open graph understands whats going on now.

For reference this article helped alot: http://davidensinger.com/2014/04/transferring-the-dns-from-namecheap-to-cloudflare-for-github-pages/

**Comment by Sambillingham** [comment]
Looking Good. :+1:  just noticed there is still a tiny bug although FB seems to be behaving anyway. The url of the og tag is relative should be absolute. 
![screen shot 2015-09-29 at 15 37 41](https://cloud.githubusercontent.com/assets/2798285/10167342/0d387546-66c0-11e5-9bc1-6b80195cdcee.png)
![screen shot 2015-09-29 at 15 36 44](https://cloud.githubusercontent.com/assets/2798285/10167345/10900a7e-66c0-11e5-8a55-00a88655190e.png)

**Comment by samjbmason** [comment]
Yeah saw it too I have opened another issues for it #43 fuxing now
